name: Build and Push to GCR

on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - ".github/**"

jobs:
   build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Build and push
        env:
          CI: false
        run: |
          echo $(ls)
          cd app
          npm install
          npm run build
          mv build/* build/.well* ../
          rm -rf node_modules
          rm package-lock.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull -q
          git checkout build --
          echo $(git status)
          cd ..
          git add .
          git commit -m 'Build'
          git push origin build

